# fly.toml app configuration file generated for parmsdatingapp on 2023-08-28T09:47:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "parmsdatingapp"
primary_region = "lhr"

[build]
  image = "parms80/parmsdatingapp:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__ApiKey = "174962611172125"
  CloudinarySettings__CloudName = "db4ogipsh"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
